name: Dependabot auto-merge
on:
  pull_request:
    types: [opened, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{github.actor == 'dependabot[bot]' && github.event.label.name == 'docker'}}
    steps:
      - name: Approve a PR
        run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
