name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - id: tags
        shell: bash
        run: |
          BASE=ghcr.io/${{github.repository}}
          BASE=${BASE,,} # lowercase
          TAGS="${BASE}:lastest,${BASE}:alpine,${BASE}:$(grep "FROM caddy:" Dockerfile | grep -v "builder" | cut -d ":" -f 2)"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{steps.tags.outputs.tags}}
      - shell: bash
        run: gh release create "$TAG" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}