name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - id: tags
        shell: bash
        run: |
          BASE=ghcr.io/${{github.repository}}
          BASE=${BASE,,} # lowercase
          TAG=$(grep "FROM caddy:" Dockerfile | grep -v "builder" | cut -d ":" -f 2)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "tags=$BASE:latest,$BASE:alpine,$BASE:$TAG" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{steps.tags.outputs.tags}}
      - shell: bash
        run: gh release create "${{steps.tags.outputs.tag}}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}