name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - id: tag
        shell: bash
        run: |
          TAG=$(grep "FROM caddy:" Dockerfile | grep -v "builder" | cut -d ":" -f 2)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags:
            - ghcr.io/${{github.repository}}/caddy-cloudflare:latest
            - ghcr.io/${{github.repository}}/caddy-cloudflare:alpine
            - ghcr.io/${{github.repository}}/caddy-cloudflare:${{steps.tag.outputs.tag}}
      - shell: bash
        run: gh release create "$TAG" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}